version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: node/Dockerfile
  node2:
    build:
      context: .
      dockerfile: node/Dockerfile
  miner1:
    build:
      context: .
      dockerfile: miner/Dockerfile
  search_agent1:
    build:
      context: .
      dockerfile: search_agent/Dockerfile

