version: '3'
services:
  node1:
    environment:
      PUB_KEY: "${NODE1_PUB_KEY}"
      PRIV_KEY: "${NODE1_PRIV_KEY}"
      GVS: "${NODE1_GVS}"
    build:
      context: .
      dockerfile: node/Dockerfile
  miner:
    build:
      context: .
      dockerfile: miner/Dockerfile
  search_agent:
    build:
      context: .
      dockerfile: search_agent/Dockerfile
  service_agent:
    build:
      context: .
      dockerfile: service_agent/Dockerfile
