version: '3'
services:
  node1:
    environment:
      PUB_KEY: "${NODE1_PUB_KEY}"
      PRIV_KEY: "${NODE1_PRIV_KEY}"
      GVS: "${NODE1_GVS}"
    build:
      context: .
      dockerfile: node/Dockerfile
    volumes:
      - ./blockchain_copies/node_blockchain:/usr/src/myapp/blockchain
  miner:
    build:
      context: .
      dockerfile: miner/Dockerfile
    volumes:
      - ./blockchain_copies/miner_blockchain:/usr/src/myapp/blockchain
  search_agent:
    build:
      context: .
      dockerfile: search_agent/Dockerfile
    volumes:
      - ./blockchain_copies/search_agent_blockchain:/usr/src/myapp/blockchain
  service_agent:
    build:
      context: .
      dockerfile: service_agent/Dockerfile
    volumes:
      - ./blockchain_copies/service_agent_blockchain:/usr/src/myapp/blockchain
  summary_manager_agent:
    build:
      context: .
      dockerfile: summary_manager_agent/Dockerfile
    volumes:
      - ./blockchain_copies/summary_manager_agent_blockchain:/usr/src/myapp/blockchain

