version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: node/Dockerfile
  miner:
    build:
      context: .
      dockerfile: miner/Dockerfile
  search_agent:
    build:
      context: .
      dockerfile: search_agent/Dockerfile
  service_agent:
    build:
      context: .
      dockerfile: service_agent/Dockerfile
